algoritmo "Exercicio_29"
// Escrever um algoritmo que mostra todos os números ímpares entre 100 e 200.
// Dica: considere a existência de um operador "mod" cujo resultado é o resto da divisão de um número por outro.

var
   cont: inteiro
inicio
      escreval("Os números ímpares de 100 até 200 são:")
      para cont de 101 ate 199 passo 2 faca
           escreval(cont)
      fimpara
fimalgoritmo
