algoritmo "Exercicio_8"
// Implemente um algoritmo que desenhe na tela os seguintes padrões:
// -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
// #=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#
// Onde cada padrão se repete 20 vezes.

var
   cont:inteiro
inicio
      para cont de 1 ate 20 faca
           escreval("-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*")
           escreval("#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#")
      fimpara
fimalgoritmo
