algoritmo "valor_negativo"
// Ler 10 valores inteiros e escrever ao final, quantos desses valores lidos são NEGATIVOS.

var
   num:inteiro
inicio

   escreval
   escreval(aluno," é aluno(a)!!!")
   enquanto (aluno <> "FIM") faca
      escreval("Digite o nome do aluno, para sair digite FIM:")
      leia(aluno)
      escreval(aluno," é aluno(a)!!!")
      naluno <- naluno + 1
   fimenquanto
   escreval("A sala tem", naluno," alunos")
fimalgoritmo
